plugins { id 'com.android.application' }

android {
    namespace 'com.teachernelly.younglearners'
    compileSdk 34

    defaultConfig {
        applicationId 'com.teachernelly.younglearners'
        minSdk 24
        targetSdk 34
        versionCode 2
        versionName '2.0'
    }

    buildTypes {
        release { minifyEnabled false }
    }
}
